export const projectData = [
  {
    projectType: "Website",
    projectName: "My Blog",
    projectDescription: "Showcases my personal blogs. Still under development!",
    projectImage: "/image1.png",
    projectUrl: "https://github.com/ananda17gb/anandas-blog",
    projectSG: "Self Project (2024-Present)",
    projectTechs: "Tech Stack: React, Tailwind CSS, and Firebase",
  },
  {
    projectType: "Website",
    projectName: "My Music Display",
    projectDescription: "Showcases my music. Still under development!",
    projectImage: "/image3.png",
    projectUrl: "https://github.com/ananda17gb/MusicDisplay",
    projectSG: "Self Project (2024-Present)",
    projectTechs: "Tech Stack: React, Tailwind CSS, and Firebase",
  },
  {
    projectType: "Mobile",
    projectName: "Food Order App",
    projectDescription: "Our Food Order App for Arjuna Chicken",
    projectImage: "/image4.png",
    projectUrl: "https://github.com/ananda17gb/arjunachicken-foodorderapp",
    projectSG: "Selft Project (2024-2024)",
    projectTechs: "Tech Stack: Flutter and Google Sheets API",
  },
  {
    projectType: "Website",
    projectName: "Sunset Snack",
    projectDescription: "A marketplace to buy food and drinks.",
    projectImage: "/image2.png",
    projectUrl: "https://github.com/athilaramdani/sunsetsnack",
    projectSG: "Group Project (2024-Present)",
    projectTechs: "Tech Stack: NextJs, Tailwind CSS, Firebase, and PostgreSQL",
  },
  {
    projectType: "Other",
    projectName: "Solitaire Game: Western Double-Six Domino",
    projectDescription: "A terminal-based domino game",
    projectImage: "/noimage.jpg",
    projectUrl: "https://github.com/ananda17gb/Domino",
    projectSG: "Group Project (2023-2023)",
    projectTechs: "",
  },
  {
    projectType: "Website",
    projectName: "Visit Temajuk",
    projectDescription:
      "Showcasing the beauty of Temajuk as a travel destination",
    projectImage: "/temajuk.png",
    projectUrl: "https://github.com/athilaramdani/sunsetsnack",
    projectSG: "Group Project (2024-2024)",
    projectTechs: "Tech Stack: Flutter and Firebase",
  },
];
